language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  - jdk_switcher use oraclejdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - oraclejdk8
  - openjdk7
script:
  - jdk_switcher use $TRAVIS_JDK_VERSION
  - mvn test -Dmaven.javadoc.skip=true

before_install:
  - wget https://github.com/zeroturnaround/zt-zip/archive/e713af91739c85709ad15bb0abf16ccffbcfb2cb.zip
  - unzip e713af91739c85709ad15bb0abf16ccffbcfb2cb.zip
  - cp -rT zt-zip-e713af91739c85709ad15bb0abf16ccffbcfb2cb ./
  - rm -r zt-zip-e713af91739c85709ad15bb0abf16ccffbcfb2cb
  - rm e713af91739c85709ad15bb0abf16ccffbcfb2cb.zip
